"""empty message

Revision ID: 1467f9e0cc97
Revises: b73cf1f500a8
Create Date: 2023-08-26 14:30:01.518444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1467f9e0cc97'
down_revision = 'b73cf1f500a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_perms', sa.Enum('none', 'view', 'post', 'edit', 'owner', 'home', name='perms'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('box', schema=None) as batch_op:
        batch_op.drop_column('default_perms')

    # ### end Alembic commands ###
